---
groups:
- name: releases
  jobs:
  - 'release-*'
- name: build
  jobs:
  - build
- name: all
  jobs:
  - build
  - 'release-*'
  - update-npm

jobs:
- name: build
  public: true
  plan:
  - in_parallel:
    - get: version
      params: { pre: rc }
    - get: repository
      trigger: true
  - task: build
    file: repository/ci/task-build.yaml
  - put: version
    params: { file: version/version }
- name: release-patch
  plan:
  - in_parallel:
    - get: version
      passed: [ build ]
      params: { bump: patch }
    - get: repository
  - task: build
    file: repository/ci/task-build.yaml
  - in_parallel:
    - put: npm-release
      params:
        path: repository
        version: version/version
        public: 'true'
    - put: github-release
      params:
        name: version/version
        tag: version/version
    - put: version
      params:
        file: version/version
- name: release-minor
  plan:
  - in_parallel:
    - get: version
      passed: [ build ]
      params: { bump: minor }
    - get: repository
  - task: build
    file: repository/ci/task-build.yaml
  - in_parallel:
    - put: npm-release
      params:
        path: repository
        version: version/version
        public: 'true'
    - put: github-release
      params:
        name: version/version
        tag: version/version
    - put: version
      params:
        file: version/version
- name: release-major
  plan:
  - in_parallel:
    - get: version
      passed: [ build ]
      params: { bump: major }
    - get: repository
  - task: build
    file: repository/ci/task-build.yaml
  - in_parallel:
    - put: npm-release
      params:
        path: repository
        version: version/version
        public: 'true'
    - put: github-release
      params:
        name: version/version
        tag: version/version
    - put: version
      params:
        file: version/version
- name: update-npm
  public: true
  plan:
  - in_parallel:
    - get: repository
    - get: weekly
      trigger: true
  - task: npm-update
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: node
          tag: alpine
      inputs:
      - name: repository
      outputs:
      - name: repository
      params:
        CI: 'true'
        FORCE_COLOR: 1
        NPM_CONFIG_FUND: 'false'
      run:
        path: sh
        args:
        - -ec
        - |
          apk add --no-cache --no-progress git 2>&1 > /dev/null
          git config --global user.name 'Felix Nehrke'
          git config --global user.email felix@nehrke.info
          cd repository
          set -x
          npm ci
          npm update
          npm audit fix --force
          npm run -- lint --fix
          npm run compile
          npm test
          git add . || true
          git commit -m 'Update npm-dependencies to their latest versions' || true
    on_failure:
      put: notify
      params:
        message: '@channel Failed to update npm dependencies'
        alert_type: failed
    on_success:
      put: repository
      params:
        repository: repository

resources:
- name: repository
  type: git
  icon: git
  webhook_token: ((webhook_token))
  check_every: never
  source:
    uri: git@github.com:nemoinho/comparator-js.git
    branch: main
    private_key: ((repository_key))
- name: version
  type: semver
  icon: tag
  check_every: never
  source:
    driver: git
    uri: git@github.com:nemoinho/comparator-js-version.git
    branch: main
    file: version
    private_key: ((repository_key))
    git_user: Felix Nehrke <feix@nehrke.info>
    initial_version: 0.0.0-rc.0
- name: notify
  type: slack-alert
  icon: slack
  source:
    url: ((slack_webhook))
- name: weekly
  type: time
  icon: clock-outline
  source:
    interval: 168h
- name: github-release
  type: github-release
  icon: github
  source:
    owner: nemoinho
    repository: comparator-js
    access_token: ((github_release_token))
- name: npm-release
  type: npm
  icon: npm
  source:
    package: "@nemoinho/comparator-js"
    registry:
      token: ((npm_auth_token))

resource_types:
- name: slack-alert
  type: registry-image
  source:
    repository: ghcr.io/arbourd/concourse-slack-alert-resource
- name: npm
  type: registry-image
  source:
    repository: timotto/concourse-npm-resource
